Repository OKAMca/stack, pull requests merged in 2024-07, with the labels that each got.

#144 Stack 178 directus block corrections
  apps/demo/app/directus-block/page.tsx
  libs/directus/directus-block/README.md
  libs/directus/directus-block/project.json
  libs/directus/directus-block/src/components/BlockSerializer/index.tsx
  libs/directus/directus-block/src/index.ts
  libs/directus/directus-block/src/server.ts
  libs/directus/directus-block/src/utils/get-block-props.ts
  libs/directus/directus-block/tsconfig.json
  libs/directus/directus-block/tsconfig.lib.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: ready to review

#146 Stack 180 directus image add an option for passing the image domain
  libs/stack/stack-ui/src/components/DirectusImg/index.tsx
  libs/stack/stack-ui/src/components/DirectusImg/interface.ts
Labels: ready to review

#143 Stack 179 cleanup release
  .github/workflows/main.yml
  README.md
  libs/directus/directus-block/project.json
  libs/directus/directus-lib/project.json
  libs/directus/directus-next-component/project.json
  libs/directus/directus-next/project.json
  libs/directus/directus-node/project.json
  libs/directus/directus-query/project.json
  libs/stack/core-lib/project.json
  libs/stack/next-component/project.json
  libs/stack/stack-ui/project.json
  nx.json
  package.json
Labels: ready to review

#148 Fix(release): workflow build packages
  .github/workflows/publish.yml
  libs/directus/directus-block/project.json
  libs/directus/directus-block/tsconfig.json
  libs/directus/directus-flexible-content/project.json
  libs/directus/directus-flexible-content/src/lib/components/FlexibleEditorContent/index.tsx
  libs/directus/directus-lib/project.json
  libs/directus/directus-next-component/project.json
  libs/directus/directus-next/project.json
  libs/directus/directus-node/project.json
  libs/directus/directus-query/project.json
  libs/stack/core-lib/project.json
  libs/stack/next-component/project.json
  libs/stack/stack-ui/project.json
  nx.json
  tsconfig.base.json
Labels: ready to review

#149 chore(release): flexible-content directory build
  libs/directus/directus-flexible-content/project.json
Labels: ready to review

#150 chore(release): flexible content access to public
  libs/directus/directus-flexible-content/package.json
Labels: ready to review

#151 fix(directus-block): export server components
  libs/directus/directus-block/package.json
  libs/directus/directus-block/vite.config.ts
Labels: ready to review

#152 fix: allow changing directus img protocol
  libs/stack/stack-ui/src/components/DirectusImg/index.tsx
  libs/stack/stack-ui/src/components/DirectusImg/interface.ts
Labels: ready to review

#155 fix(directus-flexible-content): add stack-ui and directus block to external deps
  libs/directus/directus-flexible-content/src/index.ts
  libs/directus/directus-flexible-content/src/lib/components/nodes/types.ts
  libs/directus/directus-flexible-content/vite.config.ts
  package-lock.json
Labels: ready to review

#157 fix(directus-flexible-editor): fixed content injection and prop name
  apps/demo/app/flexible-editor/page.tsx
  libs/directus/directus-flexible-content/src/lib/components/FlexibleEditorContent/index.tsx
  libs/directus/directus-flexible-content/src/lib/functions/injectDataIntoContent.ts
Labels: ready to review

#158 docs(directus-flexible-content): add documentation
  libs/directus/directus-flexible-content/README.md
Labels: ready to review

#159 fix(directus-flexible-content): support base block key for dispatching
  apps/demo/app/flexible-editor/page.tsx
  libs/directus-data-query/src/lib/gql/generated/gql.ts
  libs/directus-data-query/src/lib/gql/generated/graphql.ts
  libs/directus-data-query/src/lib/graphql/flexibleContent/test.graphql
  libs/directus/directus-flexible-content/src/lib/components/FlexibleEditorContent/index.tsx
  libs/directus/directus-flexible-content/src/lib/components/RenderNodes/index.tsx
  libs/directus/directus-flexible-content/src/lib/types.ts
Labels: question, ready to review

#160 Cep 463 directus image focal point
  libs/stack/stack-ui/src/components/DirectusImg/index.tsx
  libs/stack/stack-ui/src/components/DirectusImg/interface.ts
Labels: ready to review

#162 fix(directus-flexible-content): build fix
  libs/directus/directus-flexible-content/src/lib/components/FlexibleEditorContent/index.tsx
  libs/directus/directus-flexible-content/src/lib/components/RenderNodes/index.tsx
Labels: ready to review

#142 Stack 175 carousel accessibility
  .gitignore
  libs/stack/stack-ui/src/components/Alerts/alerts.stories.mdx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsNavigationButton.tsx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
  libs/stack/stack-ui/src/components/Alerts/index.tsx
  libs/stack/stack-ui/src/components/Alerts/interface.ts
  libs/stack/stack-ui/src/components/Carousel/carousel.stories.mdx
  libs/stack/stack-ui/src/components/Carousel/components/CarouselNavigationButton.tsx
  libs/stack/stack-ui/src/components/Carousel/components/CarouselSlide.tsx
  libs/stack/stack-ui/src/components/Carousel/components/CarouselSwiper.tsx
  libs/stack/stack-ui/src/components/Carousel/components/pagination/CarouselPagination.tsx
  libs/stack/stack-ui/src/components/Carousel/components/pagination/CarouselPaginationBullet.tsx
  libs/stack/stack-ui/src/components/Carousel/index.tsx
  libs/stack/stack-ui/src/components/Carousel/interface.ts
  libs/stack/stack-ui/src/providers/Alerts/index.tsx
  libs/stack/stack-ui/src/providers/Swiper/index.tsx
  libs/stack/stack-ui/src/providers/Swiper/interface.ts
  libs/stack/stack-ui/src/theme/Alerts/index.ts
  libs/stack/stack-ui/src/theme/Carousel/index.ts
  libs/stack/stack-ui/src/theme/index.tsx
Labels: ready to review

#137 feat(directus-next): adding draft route code
  README.md
  apps/demo/README.md
  apps/demo/app/api/draft/route.ts
  libs/directus/directus-next/README.md
  libs/directus/directus-next/src/draft/env.ts
  libs/directus/directus-next/src/draft/index.ts
  libs/directus/directus-next/src/draft/route.ts
  libs/directus/directus-next/src/index.ts
  libs/directus/directus-next/src/response.ts
  tsconfig.base.json
Labels: Merge conflicts
