Repository OKAMca/stack, pull requests merged in 2024-06, with the labels that each got.

#123 fix: aria expanded attributes not set properly on multiple items accordions
  libs/stack/stack-ui/src/components/Accordion/components/AriaAccordionItem.tsx
Labels: bug

#124 fix: alerts a11y focus carousel
  libs/stack/stack-ui/src/components/Alerts/alerts.stories.mdx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
  libs/stack/stack-ui/src/theme/Alerts/index.ts
Labels: question, ready to review

#115 STACK-72-Lib-Create-directus-block
  libs/directus/directus-block/.eslintrc.js
  libs/directus/directus-block/.storybook/.eslintrc.js
  libs/directus/directus-block/.storybook/main.ts
  libs/directus/directus-block/.storybook/preview.ts
  libs/directus/directus-block/.storybook/tsconfig.json
  libs/directus/directus-block/README.md
  libs/directus/directus-block/package.json
  libs/directus/directus-block/project.json
  libs/directus/directus-block/src/blocks/BlockWysiwyg/config.tsx
  libs/directus/directus-block/src/blocks/BlockWysiwyg/index.tsx
  libs/directus/directus-block/src/blocks/BlockWysiwyg/interface.ts
  libs/directus/directus-block/src/components/BlockDispatcher/config.ts
  libs/directus/directus-block/src/components/BlockDispatcher/index.tsx
  libs/directus/directus-block/src/components/BlockDispatcher/interface.ts
  libs/directus/directus-block/src/components/BlockSerializer/index.tsx
  libs/directus/directus-block/src/components/BlockSerializer/interface.ts
  libs/directus/directus-block/src/generated/fragment-masking.ts
  libs/directus/directus-block/src/generated/graphql.ts
  libs/directus/directus-block/src/index.ts
  libs/directus/directus-block/src/types/block.ts
  libs/directus/directus-block/src/utils/get-block-props.ts
  libs/directus/directus-block/src/utils/index.ts
  libs/directus/directus-block/src/utils/merge-configs.ts
  libs/directus/directus-block/tsconfig.json
  libs/directus/directus-block/tsconfig.lib.json
  libs/directus/directus-block/vite.config.ts
  libs/stack/stack-ui/src/index.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: ready to review

#129 fix(directus-query): fix initDirectusQuery name
  apps/demo/app/components/example.tsx
  apps/demo/app/query-example.tsx
  libs/directus/directus-query/README.md
  libs/directus/directus-query/src/index.ts
  libs/directus/directus-query/src/lib/init.ts
  libs/directus/directus-query/src/server.ts
Labels: ready to review

#128 fix: a11y on pagination for alerts
  libs/stack/stack-ui/src/components/Alerts/alerts.stories.mdx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
  libs/stack/stack-ui/src/components/Alerts/components/pagination/AlertsPagination.tsx
  libs/stack/stack-ui/src/components/Alerts/components/pagination/AlertsPaginationBullet.tsx
  libs/stack/stack-ui/src/components/Alerts/interface.ts
  libs/stack/stack-ui/src/theme/Alerts/index.ts
  package.json
  yarn.lock
Labels: ready to review

#130 fix: alert slide theme
  libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
Labels: ready to review

#132 docs: clearer blocks dispatcher doc, include blocks prop
  libs/directus/directus-block/README.md
Labels: ready to review

#135 chore: update directus-next-component readme
  libs/directus/directus-next-component/README.md
Labels: ready to review

#134 Stack 164 directus block manage server client side
  apps/demo/app/directus-block/page.tsx
  libs/directus/directus-block/src/blocks/BlockWysiwyg/index.tsx
  libs/directus/directus-block/src/components/BlockDispatcher/index.tsx
  libs/directus/directus-block/src/utils/get-block-props.ts
  libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
  libs/stack/stack-ui/src/components/Alerts/index.tsx
  libs/stack/stack-ui/src/components/Carousel/index.tsx
  libs/stack/stack-ui/src/components/fields/DatePicker/DateRangePicker.tsx
  libs/stack/stack-ui/src/components/fields/SearchField/index.tsx
  package.json
  yarn.lock
Labels: ready to review

#131 fix: alerts semantic html to theme components
  libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsNavigationButton.tsx
  libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
  libs/stack/stack-ui/src/components/Alerts/components/pagination/AlertsPagination.tsx
  libs/stack/stack-ui/src/components/Alerts/components/pagination/AlertsPaginationBullet.tsx
  libs/stack/stack-ui/src/components/Alerts/interface.ts
  libs/stack/stack-ui/src/providers/Alerts/index.tsx
  libs/stack/stack-ui/src/providers/Alerts/interface.ts
  libs/stack/stack-ui/src/theme/Alerts/index.ts
Labels: ready to review

#138 fix: all carousel elements are stylable
  libs/stack/stack-ui/src/components/Carousel/carousel.stories.mdx
  libs/stack/stack-ui/src/components/Carousel/index.tsx
  libs/stack/stack-ui/src/components/DirectusImg/index.tsx
  libs/stack/stack-ui/src/components/fields/Select/Select.interface.ts
  libs/stack/stack-ui/src/components/fields/Select/Select.tsx
  libs/stack/stack-ui/src/storybook/Menu/Menu.tsx
  libs/stack/stack-ui/src/storybook/SelectField/index.tsx
  libs/stack/stack-ui/src/theme/Carousel/index.ts
  libs/stack/stack-ui/src/theme/index.tsx
  libs/stack/stack-ui/src/types/components.ts
Labels: ready to review

#139 chore(release): refactored pipeline
  .github/workflows/publish.yml
  .github/workflows/publishing.yml
  .prettierignore
  libs/directus/directus-lib/src/lib/directus-lib.tsx
  libs/directus/directus-next-component/project.json
  libs/directus/directus-node/project.json
  libs/stack/core-lib/project.json
  libs/stack/next-component/project.json
  libs/stack/stack-ui/project.json
  libs/stack/stack-ui/src/components/fields/TextArea/index.tsx
  migrations.json
  nx.json
  package-lock.json
  package.json
  tsconfig.base.json
  yarn.lock
Labels: ready to review

#141 chore(release): fix npm token var name
  .github/workflows/publish.yml
Labels: ready to review
